### ISSUE TITLE
Cluster Autoscaler Error

### ISSUE THREAD

**Issue by toreydai** [aws-samples/eks-workshop-greater-china#10]
In Step 8.2.3
I follow all steps corretly，but when i see the logs，i see these errors:
kubectl logs -f deployment/cluster-autoscaler -n kube-system
E0313 05:22:25.497926       1 utils.go:337] Unable to build proper template node for eksctl-eksworkshop-nodegroup-ng-6ee72264-NodeGroup-1HV2SGGAPW9U3: unable to get first AvailabilityZone for ASG "eksctl-eksworkshop-nodegroup-ng-6ee72264-NodeGroup-1HV2SGGAPW9U3"

**Comment by phoenixyy** [comment]
It worked fine in my environment, with the cluster-autoscaler version of 1.1.0. 

Maybe you could first check your ASG and cluster-autoscaler pod status. Provide more information about your configuration might help if there's nothing wrong after checking.

**Comment by toreydai** [comment]
> It worked fine in my environment, with the cluster-autoscaler version of 1.1.0.
> 
> Maybe you could first check your ASG and cluster-autoscaler pod status. Provide more information about your configuration might help if there's nothing wrong after checking.

Thank you.

kubectl version:
Client Version:GitVersion:"v1.14.7-eks-1861c5"
Server Version:GitVersion:"v1.14.9-eks-502bfb"

eksctl version:
0.15.0-rc.2

awscli version:
aws-cli/1.18.19

My ASG and pod status in nothing innormal.But my cluster-autoscaler image version is 1.14.7(gcr.azk8s.cn/google-containers/cluster-autoscaler:v1.14.7).Is there something wrong with this image?

**Comment by phoenixyy** [comment]
Hi, I'm using the image of "registry.cn-hangzhou.aliyuncs.com/google-containers/cluster-autoscaler:v1.1.0" 

The version of kubectl and eksctl are the same with you.

**Comment by toreydai** [comment]
Issue fixed， my fault.
If you use the cluster_autoscler.yaml，remember to modify the auto scaling name to your own asg.

![image](https://user-images.githubusercontent.com/44282086/78107522-34b4cf00-7428-11ea-82f6-c0fed80c8520.png)
