### ISSUE TITLE
Helm repo add time out

### ISSUE THREAD

**Issue by toreydai** [aws-samples/eks-workshop-greater-china#11]
In Step 9.1
Timed out when i add these repo:
helm repo add stable https://burdenbear.github.io/kube-charts-mirror/
I use this repo instead:
helm repo add stable  http://mirror.azure.cn/kubernetes/charts/

**Comment by liangruibupt** [comment]
It is just popular Helm repo, you can use other you preferred one. 
For BurdenBear repo, you can refer below link to get help
https://github.com/BurdenBear/kube-charts-mirror
