### ISSUE TITLE
Step 4.4 使用ALB Ingress  access the ALB address report 503 error

### ISSUE THREAD

**Issue by liangruibupt** [aws-samples/eks-workshop-greater-china#16]
Step 4.4 使用ALB Ingress  access the ALB address report 503 error
```
ALB=$(kubectl get ingress -o json | jq -r '.items[0].status.loadBalancer.ingress[].hostname')
curl -m3 -v $ALB
```

**Comment by liangruibupt** [comment]
PR #15 will address the fix

**Comment by stevensu1977** [comment]
There have duplicate nginx alb ingress config  file ,  I remove other incorrect one.

**Comment by liangruibupt** [comment]
https://github.com/aws-samples/eks-workshop-greater-china/commit/cdb00aa2a907e1cb7c71e5610c55e8ccd16e638a fixed
