### ISSUE TITLE
Change/Add the kubectl to version 1.15

### ISSUE THREAD

**Issue by sesame437** [aws-samples/eks-workshop-greater-china#2]
since the EKS support v1.15, update or add the kubectl version to 1.15 in README

curl -o kubectl https://amazon-eks.s3-us-west-2.amazonaws.com/1.15.10/2020-02-22/bin/darwin/amd64/kubectl
curl -o kubectl.sha256 https://amazon-eks.s3-us-west-2.amazonaws.com/1.15.10/2020-02-22/bin/darwin/amd64/kubectl.sha256
openssl sha1 -sha256 kubectl

**Comment by pahud** [comment]
Thanks for the feedback. You are always welcome to directly edit the README and this will automatically create a PR.

Thanks.

**Comment by stevensu1977** [comment]
commit 87147e1 fix it, thanks
