### ISSUE TITLE
2.2 LoadBalancer 不工作，默认端口不能用80

### ISSUE THREAD

**Issue by ryandjf** [aws-samples/eks-workshop-greater-china#3]
问题1： kubectl apply -f resource/nginx-nlb.yaml  应该改为kubectl apply -f resource/nginx-app/nginx-nlb.yaml 

问题2： ## 下面可以试着访问这个地址
ELB=$(kubectl get service service-nginx -o json | jq -r '.status.loadBalancer.ingress[].hostname')
curl -m3 -v $ELB

不工作。echo $ELB可以看到，其实需要的是开放在80端口，但众所周知的原因，此外需要端口映射。

**Comment by stevensu1977** [comment]
问题1, Already fix ,
问题2 China Region 80/443端口会有备案流程，请联系你的商业经理完成备案流程，或者自定更改配置文件里面的端口即可。

Thanks !
