### ISSUE TITLE
add agrs for alb-ingress-controller

### ISSUE THREAD

**Issue by pinguo-yaojun** [aws-samples/eks-workshop-greater-china#31]
Because there aren't waf and wafv2 in AWS China.
So, if you use yaml file which version is v1.1.7, it must need add the args:

`- --feature-gates=waf=false,wafv2=false`

 in spec->containers->args

**Comment by stevensu1977** [comment]
@pinguo-yaojun  thanks a lot !
 I confirm this is issue reason  from 1.1.7  , default config  WAF , WAFV2 is ture 

https://github.com/kubernetes-sigs/aws-alb-ingress-controller/blob/b2a4dbf83eac0a74352fdaab4a0a186966ebe402/internal/ingress/controller/config/features.go
featureState: map[Feature]bool{
			WAF:            true,
			WAFV2:          true,
			ShieldAdvanced: true,
		},

**Comment by stevensu1977** [comment]
I already update doc, thanks your comments !
