### ISSUE TITLE
中国区镜像处理

### ISSUE THREAD

**Issue by ryandjf** [aws-samples/eks-workshop-greater-china#4]
2.4中描述的“Deploy cloudformation api-gateway.yaml，注意修改下面的镜像地址为你偏好的地址”，能否更加清楚一些？

我试着用CloudFormation 控制台或者awscli来尝试，都不work。控制台会提供AWS Lambda的问题。可能template还需要更多的修改，也请描述一下steps如何deploy.

**Comment by ryandjf** [comment]
AWS控制台的错误是：The following resource types are not supported for resource import: AWS::Lambda::Permission

**Comment by liangruibupt** [comment]
1. 只需要修改api-gateway.yaml 中 image_mirrors 下面的镜像地址为你偏好的国内镜像地址
2. 在AWS console 部署 Cloudformation template api-gateway.yaml
3. Cloudformation 部署完成之后，在 EKS 集群部署 webhook
kubectl apply -f mutating-webhook.yaml

我部署Cloudformation的结果
aws cloudformation describe-stacks --stack-name webhookforEKS --region cn-northwest-1 --query 'Stacks[0].[StackName,Description,CreationTime,StackStatus]'
[
    "webhookforEKS",
    "K8S image path mutation webhook",
    "2020-03-05T01:53:52.516Z",
    "CREATE_COMPLETE"
]

**Comment by ryandjf** [comment]
我再试了一遍，似乎API Gateway是可以的。我使用的image mirrors如下：
          image_mirrors = {
            'gcr.io/': 'gcr.azk8s.cn/',
            'k8s.gcr.io/': 'gcr.azk8s.cn/google-containers/',
            'quay.io/': 'quay.azk8s.cn/'
          }

部署到AWS后，如果我到API Gateway 测试获得的返回值base64 decode一下是：
[{"path": "/spec/containers/0/image", "value": "gcr.azk8s.cn/nginx:latest", "op": "replace"}]
说明API Gateway是好的。

然后，修改mutating-webhook.yaml如下：
clientConfig:
        url: "https://b0wywsdwy6.execute-api.cn-northwest-1.amazonaws.com.cn/call"
再运行：
$ kubectl apply -f mutating-webhook.yaml
$ kubectl apply -f ./nginx-gcr.yaml
$ kubectl get pod nginx-gcr-deployment-784bf76d96-hjmv4 -o=jsonpath='{.spec.containers[0].image}'

得到的仍然是k8s.gcr.io/nginx，说明webhook没有工作。

**Comment by liangruibupt** [comment]
You can check whether your API GW / Lambda has been invoked and check the logs of lambda to see any error when modify the image mirror path.

**Comment by ryandjf** [comment]
同样的步骤，我在香港区试了一下是可以work的。会不会是中国区的EKS没有enable dynamic mutation webhook?

**Comment by ryandjf** [comment]
原来是备案的原因...
