### ISSUE TITLE
eksctl 0.36.0-rc1 causes partition error

### ISSUE THREAD

**Issue by dz902** [aws-samples/eks-workshop-greater-china#42]
`eksctl` version in the doc is very old and needs some update. Current version has aws partition problems.

![4](https://user-images.githubusercontent.com/2723003/156350164-d2ba3f22-6fb0-4ed0-9020-56808ad726eb.png)

**Comment by stevensu1977** [comment]
you can follow v0.62.0 or other later version .

#eksctl 版本 > v0.62.0
curl -L "https://github.com/weaveworks/eksctl/releases/download/0.62.0/eksctl_$(uname -s)_amd64.tar.gz" | tar xz -C .
sudo mv ./eksctl /usr/local/bin
