### ISSUE TITLE
efs-csi-driver issue

### ISSUE THREAD

**Issue by toreydai** [aws-samples/eks-workshop-greater-china#7]
In Step 6.1
aws efs create-mount-target --file-system-id FileSystemId --subnet-id SubnetID --security-group SGGroupID
SubenetID is not specified，so it didn't work.I use AWS console to create mount target，and it worked.

**Comment by liangruibupt** [comment]
Please update FileSystemId , SubnetID， SGGroupID based on your environment
I will update the document
