### ISSUE TITLE
HPA sample application php-apache issue

### ISSUE THREAD

**Issue by toreydai** [aws-samples/eks-workshop-greater-china#9]
In Step 8.1.2
In the beginning，you need to deploy php-apache first.
Below is the command:
kubectl apply -f https://k8s.io/examples/application/php-apache.yaml

**Comment by liangruibupt** [comment]
No need, below command will deploy php-apache 
kubectl autoscale deployment php-apache --cpu-percent=30 --min=1 --max=5

**Comment by toreydai** [comment]
kubectl autoscale deployment php-apache --cpu-percent=30 --min=1 --max=5
Error from server (NotFound): deployments.extensions "php-apache" not found
